### ISSUE TITLE
Batch Upload

### ISSUE THREAD

**Issue by mesoller** [z-ink/Uploadrr#16]
Thanks for give a life for L4G uploader.

I'm using your script and I can see this text:

  ——— Processing # 1 of 1 ———

Does this mean, this script is capable for batch upload? If, yes how to set it up?

**Comment by z-ink** [comment]
Multiple ways. 
Either multilink in your arg. 
Ex: `python3 upload.py "path/to/video1.mkv" "path/to/tvseries2"`
or as GME points out, use -aq `python3 upload.py -aq "path/to/folder"` this will automatically queue up movies/series in path. the -fa flag triggers unattended on all of this so use sparingly.
