### ISSUE TITLE
Feature Request: New Flag to preserv original Encode 

### ISSUE THREAD

**Issue by 0utlawActual** [z-ink/Uploadrr#17]
After last few releases H.264 or x264 automatically get converted as AVC in the the title. While technically they are AVC, some PTs like to see the original encode in the titles as uploads get flagged for review. Please consider adding a flag that would preserver original and not convert to AVC. Looking at the Argument list on  `https://theldu.org/index.php/Uploadrr` I don't see such an option as of now.

Thanks for your consideration

**Comment by z-ink** [comment]
Hi, back from vacay here playing catch up. That was due to a very silly error on my part. Patched a duplication of codec issue only to have it ignore the type/format for codec. Please update and let me know if issue is resolved. Sorry for the inconvenience.

**Comment by 0utlawActual** [comment]
Will report back as soon as I do next upload. Thank you!

**Comment by 0utlawActual** [comment]
Confirmed to be working as intended now
