### ISSUE TITLE
404 error on upload

### ISSUE THREAD

**Issue by Lusephur** [z-ink/Uploadrr#8]
Suddenly happened. was uploading a folder of films, first two films uploaded, and then this message appeared
`Upload to LDU?  [y/n]: y
Uploading to LDU
Searching for existing torrents on site...
No dupes found
Encountered Error: 404 Client Error: Not Found for url: https://theldu.to/api/torrents/upload?api_token=
May have uploaded, please go check..
Status of upload is unknown, please go check..`

Obviously, the file has not uploaded, otherwise, I wouldn't be hassling you. 
Not sure what is happening. Nothing errors out when running debug. And swarmazon uploads fine.

**Comment by Lusephur** [comment]
Ignore this. Seems the api does not like the use of ":" in filenames.
Ran the previous version of Upload.py, and the error there explains it, slightly.

**Comment by Lusephur** [comment]
Closed

**Comment by z-ink** [comment]
> Ignore this. Seems the api does not like the use of ":" in filenames. Ran the previous version of Upload.py, and the error there explains it, slightly.

Thank you. I will amend the code to post the server response in full if you're given an error. 404 is what's happening as you're not getting a page but yeah the server would tell you something along the lines of invalid characters. Which i took off by accident in favor of a cleaner success or failure (not useful for debugging) also debug does nothing here as it doesnt post anything to the server so ofc you'd not get any response.
